f = open("D:/word.txt", "w", encoding = "UTF-8")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.write("Welcome to New York!")
f.flush()
input()
f.close()