print("Hello", end="\n")
print("World", end="\n")
print("Hello", end=" ")
print("World", end=" ")
print("\n")
print("abc 你好")
print("a 你好")
print("a\t\t你好")
print("abc\t\t你好")
print("abcde\t你好")